---
title: "tips"
author:
  - 小鹤
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes 
    toc: yes
classoption: "hyperref,"
---

# 网络管理
1. 载入igraph包

```{r warning=FALSE}
# 载入igraph包
library(igraph)
```

```{r}
set.seed(10)
g1 <- sample_smallworld(1, 200, 5, 0.05)
vcount(g1)
ecount(g1)
# 图的直径
diameter(g1)
# 图的密度
edge_density(g1)
# 点的相邻点 ego（graph，length，node）   length 相隔几个点  node 哪个点
unlist(ego(g1,1,10))


```



2. 简单的图
```{r}
g1<-graph(edges = c(1,3,2,5,4,1,5,3),n=6,directed = F)
plot(g1)
# 查看属性,U 代表无向图   
print(g1)
```






# 绘图
```{r}
# cex 点的大小， pch 点的样式, col 点的颜色，多个表达方式，其中alpha可为透明度
plot(x=1:10,y=rep(2,10),cex=5,col="dark red",pch=19,ylim = c(0,10))
points(x=1:10,y=rep(4,10),cex=3,col="557799",pch=2)
points(x=1:10,y=rep(6,10),cex=1,col=rgb(.2,.5,.7,alpha = .5),pch=4)
points(x=1:10,y=rep(8,10),cex=7,col=rgb(123,45,209,maxColorValue = 255),pch=18)
#line(x=1:10,y=rep(9,10),col="red")
```



# 内存管理
```{r}
# 全部清理
rm(list=ls())
# 清理某一个
a<-10
rm(a)

```


# 绘制函数图像

```{r}
fun_cal<-function(x){
  
  a<-10
  # beta IBK  个人教育背景
  beta<-1
  # omega FR 忘记因素
  omega<-3
  # sigma   对谣言源头的信任度
  sigma<-10
  y<-a*exp((-1)*beta*x)*cos(omega*x+sigma)
  y[which(y<0)]<-y[which(y<0)]*(-1)
  return(y)
}

plot_fua<-function(fm,to,by){
  x<-seq(fm,to,by)
  y<-fun_cal(x)
  plot(x,y)
  lines(x,y)
}
```





















